### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by mcrypt-nn**

### CODE REVIEW

**Comment by DeckerSU** [comment]
According to [bible](https://github.com/KomodoPlatform/dPoW/blob/dev/doc/bible.md):

```
Notary nodes achieving a regional top 3 ranking at the ranking snapshot date are automatically re-elected to operate that node in the next season.

Notary nodes achieving a regional top 5 ranking are eligible to submit a candidacy for an additional notary node for each region they held a top 5 position in at the ranking snapshot date.

Notary nodes who are not in their regional top 5 at the end of the season can reapply for a single node for each of the region(s) they served in during the previous season.
```

Plz fix number of nodes you applied, according to that.

**Comment by TheComputerGenie** [comment]
How does
`No notary can hold more than 2 nodes in a single region, or more than 6 nodes in total.`
not apply in this situation (with mcrypt_SH being in the Top 3)?

**Comment by mcrypt-nn** [comment]
English is not main language. But this rule means you cannot operate new node in new region if you are a old notary operator?
I can never ever run node in AR because i have one in SH?

**Comment by mcrypt-nn** [comment]
@smk762 @ca333 please clarify as it's not clear?

**Comment by smk762** [comment]
Top 3 means you keep node in the region you were top 3.
Top 5 means you get a chance at one extra node (in any region). 
Not in top 5 veterans can reapply for a chance at the nodes held last season.

So if you win top 3, congrats, you keep your node without needing to be voted in for it (same region as you won in).
This means you are also in top 5, which means you get a chance to apply a proposal for one extra node (in any region).

The next bit does not apply to you because you are in top 5.
_Notary nodes who are **not in their regional top 5** at the end of the season can reapply for a single node for each of the region(s) they served in during the previous season._

So if you got top 3 in one region, and didn't operate in any other regions. So you keep your node in SH, and can submit a proposal for **one** more node in **any** region.

**Comment by mcrypt-nn** [comment]
@smk762 thank you I changed the page now

**Comment by smk762** [comment]
thanks, and good luck!

**Pull request merged**
