### PR TITLE
Removing EU spot

### PR DESCRIPTION
**Pull request by StrobFX**
Sorry I realized I have to remove 1 spot to comply with current s4 rules from the bible.

### CODE REVIEW

**Comment by gcharang** [comment]
hey, can you also update the table in this file? https://github.com/KomodoPlatform/NotaryNodes/blob/master/season4/candidates/README.md

**Comment by StrobFX** [comment]
I updated the table for all new changes in the new PR but kbtworks didn't specify a region so I alerted him.

**Comment by StrobFX** [comment]
Finally it's creating a conflict, Do you know why gcharang?

**Comment by StrobFX** [comment]
Ok I think i resolved it.

**Pull request merged**
